apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    app.kubernetes.io/name: nginx
    app.kubernetes.io/component: webserver
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        app.kubernetes.io/name: nginx
        app.kubernetes.io/component: webserver
    spec:
      containers:
      - name: nginx
        image: registry.redhat.io/rhel8/nginx-120:latest
        # İmajın sessizce kapanmasını engelleyip, S2I altyapısını foreground'da tutuyoruz
        command: ["/usr/libexec/s2i/run"]
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: NGINX_CONTAINER_RUN_AS
          value: nginx
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        volumeMounts:
        # 1. Aşama: HTML dosyasının duracağı güvenli dizin
        - name: html-volume
          mountPath: /tmp/html
        # 2. Aşama: Nginx'e bu dizini tanıtacak küçük konfigürasyon dosyası
        - name: config-volume
          mountPath: /etc/nginx/default.d/custom-root.conf
          subPath: custom-root.conf
      volumes:
      - name: html-volume
        configMap:
          name: index-html
          defaultMode: 420
      - name: config-volume
        configMap:
          name: nginx-custom-config
          defaultMode: 420
