apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: product-catalog-pre-prod

resources:
  - ../../

commonLabels:
  environment: pre-prod

replicas:
  - name: server
    count: 2
  - name: client
    count: 2
