apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: product-catalog

resources:
  - ../../components/client/base
  - ../../components/server/base
  - ../../components/database/base

commonLabels:
  environment: pre-prod

replicas:
  - name: server
    count: 2
  - name: client
    count: 2
