apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: server
spec:
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: client
spec:
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: None
