apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: product-catalog-prod

resources:
  - ../../

commonLabels:
  environment: prod

replicas:
  - name: server
    count: 4
  - name: client
    count: 4

patchesStrategicMerge:
  - patches/db-pvc-size.yaml
  - patches/secure-route.yaml
